#!/usr/bin/env python3
# ---------------------------------------------------------
#   Name: checkpointer.py
#   Author: xyy15926
#   Created: 2026-04-21 19:53:32
#   Updated: 2026-04-23 18:25:11
#   Description:
# ---------------------------------------------------------

# %%
import logging
from typing import Dict, List, Callable, Any, Optional
import json
import hashlib
from functools import wraps
import threading
from datetime import datetime, timedelta
# from IPython.core.debugger import set_trace

if __name__ == "__main__":
    from importlib import reload
    from flagbear.slp import finer, storage, serializer
    reload(finer)
    reload(storage)
    reload(serializer)
from flagbear.slp.storage import StorageBackend, LocalFileStorage
from flagbear.slp.finer import date_order_mark
from flagbear.slp.serializer import serialize, deserialize

logging.basicConfig(
    format="%(module)s: %(asctime)s: %(levelname)s: %(message)s",
    level=logging.INFO,
    force=(__name__ == "__main__"),
)
logger = logging.getLogger()
logger.info("Logging Start.")


# %%
class CheckpointManager:
    def __init__(
        self,
        storage: Optional[StorageBackend] = None,
        override: bool = True,
        force: bool = False,
        ttl: Optional[timedelta] = None,
        on_hit: Optional[Callable[[str], None]] = None,
        on_miss: Optional[Callable[[str], None]] = None,
    ):
        self.storage = storage or LocalFileStorage()
        self.override = override
        self.force = force
        self.ttl = ttl
        self.on_hit = on_hit
        self.on_miss = on_miss
        self._stats = {"hits": 0, "misses": 0, "errors": 0}
        self._stats_lock = threading.Lock()

    def checkpoint(
        self,
        func: Optional[Callable] = None,
        *,
        force: bool = False,
        override: bool = True,
        version: Optional[str] = "v1",
        ttl: Optional[timedelta] = None,
        ser_type: Optional[str] = None,
        skip_args: Optional[List[int, str]] = None,
        keyonly_args: List[str] = None,
    ) -> Callable:
        """Checkpoint decorator to cache functions' result.

        Note that: 
        1. User shouldn't set both `override` and `force` as this
          will lead to function call every time and the result history calls
          will be overridden.
        2. Keyword parameter `force` is allowed for the decorated function
          if user wants a brand-new result.

        Attention:
        1. It should be careful to unset `override` as no lock is held to
          ensure the no more caches is generated by other threads with the
          key constructed with date-order-mark.

        Params:
        -------------------------------
        func: Function to be decorated.
        version: Version of the function that should be updated by the user
          manually when the function's function changed?
        override: If to override the older cache.
        force: If to force to call the `func` everytime instead of load the
          cache.
        ttl: Time till live.
        skip_args: Index of positional arguments or key or keywords arguments
          that should be skipped to construct the cache-key.
        ser_type: How to serialize the result.
        """
        def decorator(ffunc: Callable) -> Callable:
            nonlocal ttl, override, self, force, ser_type
            ttl_ = ttl if ttl is not None else self.ttl
            override_ = override if override is not None else self.override
            @wraps(ffunc)
            def wrapper(*args, **kwargs) -> Any:
                # set_trace()
                nonlocal force, override_, ser_type
                # Pop the keyword arugment `force` out.
                force_ = kwargs.pop("force", None)
                force_ = force_ if force_ is not None else force
                if not force_:
                    # Get the existing key with `override=True`.
                    key = self.gen_key(
                        ffunc, args, kwargs, version,
                        skip_args, True,
                    )
                    result = self.get(key)
                    if result is not None:
                        return result

                # Roll back to call `func` to get the result.
                result = ffunc(*args, **kwargs)
                meta = {
                    "created_at": datetime.now().isoformat(),
                    "type_": ser_type,
                }
                if ttl_ is not None:
                    meta["expires_at"] = (datetime.now() + ttl_).isoformat()

                # Construct key with considerring if to override existing
                # cache.
                key = self.gen_key(
                    ffunc, args, kwargs, version,
                    skip_args, override_,
                )
                self.set(key, result, meta)

                return result
            return wrapper

        # `@checkpoint`：decorate the `func` directly with the default setting
        # `@checkpoint()`: return the inner decorator with customed setting
        return decorator(func) if func else decorator

    def get(self, key: str) -> Any:
        """Get and deserialize data with key."""
        bytes_ = self.storage.get(key)
        # set_trace()
        # Hit cache.
        if bytes_ is not None:
            try:
                result = self.deserialize(bytes_)
                with self._stats_lock:
                    self._stats["hits"] += 1
                if self.on_hit:
                    self.on_hit(key)
                return result
            except Exception as e:
                logger.warning(f"Failed to deserialize the cache data: {e}.")
                self.storage.delete(key)
                return None
        # Miss cache.
        else:
            with self._stats_lock:
                self._stats["misses"] += 1
            if self.on_miss:
                self.on_miss(key)
        return None

    def set(self, key: str, data: Any, meta: Dict = None):
        """Serielize and set data with key."""
        # set_trace()
        try:
            bytes_, meta = self.serialize(data, meta)
            self.storage.set(key, bytes_, meta)
        except Exception as e:
            logger.warning(f"Failed to serialize and save the data: {e}.")
            with self._stats_lock:
                self._stats["errors"] += 1

    @classmethod
    def serialize(cls, data: Any, meta: Dict = None) -> bytes:
        """Serialize data into bytes with meta."""
        meta = meta or {}

        # Use specified `type_` if passed.
        type_ = meta.get("type_")
        bytes_, type_ = serialize(data, type_)
        meta["type_"] = type_

        # Concat meta-length, meta and data.
        meta_bytes = json.dumps(meta).encode("utf8")
        meta_size = len(meta_bytes).to_bytes(4, "big")
        bytes_ = meta_size + meta_bytes + bytes_

        return bytes_, meta

    @classmethod
    def deserialize(cls, bytes_: bytes) -> Any:
        """Deserialize data bytes from cache."""
        # Get metadata from data bytes.
        meta_size = int.from_bytes(bytes_[:4], "big")
        meta = json.loads(bytes_[4: 4 + meta_size].decode("utf8"))
        result = deserialize(
            bytes_[4 + meta_size:],
            meta["type_"]
        )
        return result

    def gen_key(
        self,
        func: Callable,
        args: Any,
        kwargs: Any,
        version: str = "v1",
        skip_args: List = None,
        override: bool = True,
    ) -> str:
        """Concate function name with arguments.

        Only the int, float and str argument will be used to construct the name
        that will be used as the key or identifier.

        Params:
        -----------------------------
        func: Callable.
        args: List of positional arguments.
        kwargs: Dict of keywords arguments.
        vesion: The `func` version, which should be control by user-self.
        skip_args: Index of positional arguments or key or keywords arguments
          that should be skipped before hashing.
        override: If to return the existing newest key.

        Return:
        -----------------------------
        String as the key or identifier.
        """
        prefix = concat_params(func, args, kwargs, version, skip_args)
        exists_keys = self.storage.list_keys(prefix)
        if len(exists_keys) == 0:
            key = date_order_mark(prefix, exists_keys, "today", 1)
        elif override:
            key = date_order_mark(prefix, exists_keys, None, 0)
        else:
            key = date_order_mark(prefix, exists_keys, "today", 1)
        return key

    def clear_func_cache(self, func: Callable, version: str = ""):
        """Clear function cache.

        Cache of all versions will be cleared by default.
        """
        prefix = f"{func.__module__}.{func.__qualname__}_{version}"
        for key in self.storage.list_keys(prefix):
            self.storage.delete(key)

    def stats(self) -> dict:
        """Return the checkpoint status."""
        return dict(self._stats)


# %%
def concat_params(
    func: Callable,
    args: List[Any],
    kwargs: List[str, Any],
    version: str = "v1",
    skip_args: List = None,
) -> str:
    """Concate function name with arguments.

    Only the int, float and str argument will be used to construct the name
    that will be used as the key or identifier.

    Params:
    -----------------------------
    func: Callable.
    args: List of positional arguments.
    kwargs: Dict of keywords arguments.
    vesion: The `func` version, which should be control by user-self.
    skip_args: Index of positional arguments or key or keywords arguments
      that should be skipped before hashing.

    Return:
    -----------------------------
    String as the key or identifier.
    """
    if skip_args:
        args = tuple(a for i, a in enumerate(args) if i not in skip_args)
        kwargs = {k: v for k, v in kwargs.items() if k not in skip_args}
    # set_trace()
    try:
        arg_str = json.dumps((args, kwargs), sort_keys=True, default=str)
    except (TypeError, ValueError):
        arg_str = str((args, kwargs))
    arg_str = hashlib.md5(arg_str.encode("utf8")).hexdigest()[:16]
    ret = f"{func.__module__}.{func.__qualname__}_{version}_{arg_str}"
    return ret
